### PR TITLE
actually render leashes

### LINKED ISSUE #7: server game bug
My version is 1.20.1. In the local game, I can lead bot player, and the lead is displayed correctly. In the server game, I can lead other players, but the lead isn't displayed.

### PR DESCRIPTION
**Pull request by RoootTheFox**
This makes leashes render (even in multiplayer/on servers)
Yes, this is a one-line fix.

Fixes #7.

Preview:
image
image

(i also bumped the version to 1.0.4 since this is a feature addition)

### CODE REVIEW

**Comment by RoootTheFox** [comment]
small side note: i noticed the mod version on modrinth is 1.0.5, did you maybe forget to push some code to the repository?

if so, i'd advice doing that and then just bumping the version to 1.0.6

**Comment by RoootTheFox** [comment]
just found out that this breaks outside the development environment for some reason, gotta investigate and fix.

**Comment by RoootTheFox** [comment]
i did some digging, it appears to not even spawn the LeashProxyEntity outside of the dev environment.

**Comment by RoootTheFox** [comment]
I found the solution!
I force pushed the branch to get rid of my previous (failed) attempt lmao

going to really quickly bump the version now

**Comment by pog5** [comment]
Thanks! I'm just going to let the CI test the version and I'll merge it :)

**Comment by pog5** [comment]
Thanks 👍

**Pull request merged**
